### ISSUE TITLE
img2fb doesn't compile

### ISSUE THREAD

**Issue by NeonLightning** [AreaScout/Gaming-Kit-Tools#1]
i don't have it with me to show the error right now but img2fb is the only part that won't compile when running in ORA 1.5.2

**Comment by AreaScout** [comment]
Without more information it's hard to tell what fails

**Comment by NeonLightning** [comment]
here we go.

img2fb.cpp: In function ‘int main(int, char**)’:
img2fb.cpp:46:20: error: ‘nullptr’ was not declared in this scope
  const char *opt = nullptr;
                    ^
Makefile:14: recipe for target 'img2fb' failed
make: *** [img2fb] Error 1`

**Comment by AreaScout** [comment]
thank you for reporting :) fixed in 2e46909
